### ISSUE TITLE
parent component state in child component

### ISSUE THREAD

**Issue by appsdevpk** [jegan321/nuro#15]
i am trying to create a component that will display a list of contents based on props, i am passing content type name to this component from the parent component, but the problem is i can only access this prop in template, what if i want its value in afterMount lifecycle hook, there i will fetch that content type from server and update the state of this component, but the value i am getting for this prop is an empty string in afterMount hook

**Comment by jegan321** [comment]
To access props in a method on your component you can do `this.props.xxx`. Here is an example:

```js
    class App {
      template = '<div>Hello {{props.name}}</div>'
      afterMount() {
        alert('Hello ' + this.props.name)
      }
    }

    let props = {
      name: 'World'
    }

    Nuro.mount(App, null, props)
```

That's my fault for not including it in the docs. I'll update it when I get a chance.

**Comment by appsdevpk** [comment]
got it, thanks for the reply
