### ISSUE TITLE
Add a "Nuro.register" alias/replacement for Nuro.include

### ISSUE THREAD

**Issue by RollingHog** [jegan321/nuro#17]
No idea why google brought me here after "reactive components only framework js" request but god I like what I see. Hope it won't go down the bloatware avenue over the years. Sorry for offtopic, got a little overexcited. 

Title is pretty self-explanatory. First, even in readme you use a word "register" 
> Or register a component globally

And second, it is pretty much a default word for such operation in framework world since it perfectly describes what's happening here.

This request is purely aesthetical and can be closed with resolution "No, I like it like this" without hesitation anyway.

**Comment by jegan321** [comment]
I'm glad you like the project! If you end up building something with it I would love to see it.

I actually agree that register is a better word than include. When I get a chance I will add the alias. I'm thinking I will probably deprecate `include` and then remove it in a future release.

**Comment by RollingHog** [comment]
Pretty sure I'll use instead of Vue where Vue is "too much" ^_^ Will link as soon as I do something not under NDA

Glad to hear, leaving this issue opened then.

**Comment by jegan321** [comment]
`Nuro.register()` is added in version 0.5.4! Thanks for the feedback.
