### ISSUE TITLE
Nuro is already a trademark

### ISSUE THREAD

**Issue by RollingHog** [jegan321/nuro#18]
Self-explanatory. It is a US robotics company:
https://www.google.com/search?q=nuro
Not really a big one but still.
Maybe consider renaming to nurojs or something like this to avoid that Azer Koçulu moment later?

**Comment by jegan321** [comment]
Yeah the name being taken already is unfortunate. I found out about the robotics company a couple of months after I started using the name for this project but I never thought of something else to change it to. It's pretty difficult to find a word that isn't already taken on npm! I'm not too worried about it right now but I may end up changing it in down the road.

**Comment by RollingHog** [comment]
Understandable, but I can do some research (i.e googling) to find some other name. Did you have some idea in your mind while naming lib "nuro" or is it just a random word?

**Comment by RollingHog** [comment]
Possible idea: Nyro. The only name is some singer https://www.google.com/search?q=nyro

Other random thing is girdo (some obscure food https://www.google.com/search?q=girdo )

Both are avaliable at npm

**Comment by jegan321** [comment]
I appreciate the effort but to be honest I don't want to change the name at this point. I'm going to close this issue for now.
